apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-logging-service
  template:
    metadata:
      labels:
        app: audit-logging-service
    spec:
      containers:
        - name: audit-logging-service
          image: audit-logging-service:latest
          ports:
            - containerPort: 9093
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-audit:5432/AuditLoggingService
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: alwis
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka