apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-claims-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-claims-service
  template:
    metadata:
      labels:
        app: billing-claims-service
    spec:
      containers:
        - name: billing-claims-service
          image: billing-claims-service:latest
          ports:
            - containerPort: 9094
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-billing:5432/BillingClaimsService
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: alwis
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka