apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-inventory
  template:
    metadata:
      labels:
        app: db-inventory
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_DB
              value: InventoryService
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: alwis
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: inventory-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: inventory-data
          hostPath:
            path: /data/db-inventory
            type: DirectoryOrCreate