apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer  # Expose externally via Minikube