apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharmacy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharmacy-service
  template:
    metadata:
      labels:
        app: pharmacy-service
    spec:
      containers:
        - name: pharmacy-service
          image: <dockerhub-username>/pharmacy-service:latest
          ports:
            - containerPort: 9194
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db-pharmacy:5432/PharmacyService
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: alwis
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka